### ISSUE TITLE
Simpletest example failing inconsistently 

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_Qualia#6]
The basic example from the connection manager library runs fine:
https://github.com/adafruit/Adafruit_CircuitPython_ConnectionManager/blob/main/examples/connectionmanager_helpers.py
over and over, reboot after reboot. Can not get it to fail.
```python
code.py output:
----------------------------------------
Fetching from http://wifitest.adafruit.com/testwifi/index.html
Text Response This is a test of Adafruit WiFi!
If you can read this, its working :)
----------------------------------------

Code done running.
```

The simpletest example from this library:
https://github.com/adafruit/Adafruit_CircuitPython_Qualia/blob/main/examples/qualia_simpletest.py
fails inconsistently.

With that simpletest example saved to `CIRCUITPY` as `code.py` and going through several soft resets, get the following:

Example failed output:
```python
code.py output:
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
Connecting to AP peanuthamper
Retrieving data...Traceback (most recent call last):
  File "adafruit_connection_manager.py", line 271, in get_socket
OSError: [Errno 113] ECONNABORTED

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "code.py", line 19, in <module>
  File "adafruit_portalbase/__init__.py", line 454, in fetch
  File "adafruit_portalbase/network.py", line 645, in fetch_data
  File "adafruit_portalbase/network.py", line 563, in fetch
  File "adafruit_requests.py", line 591, in get
  File "adafruit_requests.py", line 525, in request
  File "adafruit_connection_manager.py", line 282, in get_socket
RuntimeError: Error connecting socket: [Errno 113] ECONNABORTED

Code done running.
```

Another example:
```python
code.py output:
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
Connecting to AP peanuthamper
Retrieving data...Traceback (most recent call last):
  File "code.py", line 19, in <module>
  File "adafruit_portalbase/__init__.py", line 454, in fetch
  File "adafruit_portalbase/network.py", line 645, in fetch_data
  File "adafruit_portalbase/network.py", line 563, in fetch
  File "adafruit_requests.py", line 591, in get
  File "adafruit_requests.py", line 525, in request
  File "adafruit_connection_manager.py", line 236, in get_socket
gaierror: (-2, 'Name or service not known')

Code done running.
```

And then randomly, sometimes, it works:
```python
code.py output:
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
Connecting to AP peanuthamper
Retrieving data...Reply is OK!
----------------------------------------
This is a test of Adafruit WiFi!
If you can read this, its working :)
----------------------------------------

Code done running.
```

**CP info:**
```python
Adafruit CircuitPython 9.0.2 on 2024-03-28; Adafruit-Qualia-S3-RGB666 with ESP32S3
```

**Comment by makermelissa** [comment]
It could be something to do with the interaction of PortalBase and the new connection manager. I wonder if other "portal" projects have similar issues.

**Comment by justmobilize** [comment]
Since `ConnectionManager` is mostly refactored code from `Requests` it shouldn't of broken anything. 

You can download a previous version of `Requests` from [here](https://github.com/adafruit/Adafruit_CircuitPython_Requests/releases/tag/2.0.5). This version doesn't use the `ConnectionManager`

**Comment by makermelissa** [comment]
What I meant was that PortalBase might have been doing something weird with regards to network connections because it was trying to work on a couple of different connection methods and may need to be adjusted to changes that have happened over time. ConnectionManager consolidates all of the different methods and simplifies things greatly, so PortalBase network functions may just be overly complicated at this point.
